Хранилище
htmlacademy-react/1949499-what-to-watch-10 pull request #8
Opened 2022-08-23 10:40 UTC by LexusEgorov

Добрый день! По семейным обстоятельствам "успешно" потерял неделю. Как лучше сейчас поступить? Может быть, самостоятельно делать ПР через интерфейс защиты? 
Сейчас изолировался от мира. Планирую доделать проект по базовым критериям к 28-29 числу. Если самостоятельно буду принимать ПР, то успеваю, вроде как.

2022-08-24 03:02 UTC, Dima-Dim requested changes

2022-08-24 03:02 UTC, Dima-Dim commented on project/src/components/genres-list/genres-list.tsx
> +        [...genres].map((genre) => (
Для чего тут деструктурихация `genres`?

2022-08-24 03:02 UTC, Dima-Dim commented on project/src/components/genres-list/genres-list.tsx
> +          <li className={`catalog__genres-item ${currentGenre === genre ? 'catalog__genres-item--active' : ''}`} key={genre}>
https://www.npmjs.com/package/classnames

2022-08-24 03:03 UTC, Dima-Dim commented
> Добрый день! По семейным обстоятельствам "успешно" потерял неделю. Как лучше сейчас поступить? Может быть, самостоятельно делать ПР через интерфейс защиты? Сейчас изолировался от мира. Планирую доделать проект по базовым критериям к 28-29 числу. Если самостоятельно буду принимать ПР, то успеваю, вроде как.
> 
> mortar_board [Контроль и ограничения (часть 1)](https://up.htmlacademy.ru/react/10/user/1949499/tasks/9)

Зависит от того, какая у тебя цель, если максимально быстро выйти на защиту, то да, можешь принимать автоматически, если в процессе получения иметь возможность получить обратную связь, то нет :)

2022-08-24 03:17 UTC, LexusEgorov commented on project/src/components/genres-list/genres-list.tsx
> +        [...genres].map((genre) => (
Я так set в массив преобразую. Можно сделать проще?

2022-08-24 03:44 UTC, Dima-Dim commented on project/src/components/genres-list/genres-list.tsx
> +        [...genres].map((genre) => (
Ммм, не заметил что `genres` это Set.

2022-08-25 21:16 UTC, LexusEgorov commented
Добавил селекторы. Насколько корректно?
Заметил, что при смене экрана, появляется ошибка: невозможно обновить компонент, пока рендерится другой компонент.
Например, перехожу с главного экрана на страницу фильма. Невозможно обновить список жанров (их вообще тут нет), пока рендерится 'страница фильма'.
Вообще нет идей из-за чего такое возникает. Дайте пинка в каком месте искать ошибку :)

2022-08-26 03:59 UTC, Dima-Dim commented
> Добавил селекторы. Насколько корректно? Заметил, что при смене экрана, появляется ошибка: невозможно обновить компонент, пока рендерится другой компонент. Например, перехожу с главного экрана на страницу фильма. Невозможно обновить список жанров (их вообще тут нет), пока рендерится 'страница фильма'. Вообще нет идей из-за чего такое возникает. Дайте пинка в каком месте искать ошибку :)

Оставил комментарий к коду с ссылкой на пример селектора из учебного проекта. За одно можешь посмотреть уже сам где и как они используются.

Копать в консоль, всегда и в первую очередь, обычно там бывает более понятная информация о том, где и что пошло не так.

2022-08-26 04:30 UTC, LexusEgorov commented
![изображение](https://user-images.githubusercontent.com/75787214/186822316-438c0925-eae3-408d-81db-975f9c39448c.png)
Не понимаю, у меня даже setState нет в этих компонентах.
А где комментарий? Не могу найти

2022-08-26 04:47 UTC, Dima-Dim commented
> ![изображение](https://user-images.githubusercontent.com/75787214/186822316-438c0925-eae3-408d-81db-975f9c39448c.png) Не понимаю, у меня даже setState нет в этих компонентах. А где комментарий? Не могу найти

Тут сказано про setState внутри filmScreen.

2022-08-26 04:59 UTC, LexusEgorov commented
В filmScreen тоже нет setState. Но ошибка возникает вообще по компоненту GenresList. Он находится в mainScreen. 
Не могу понять, что вызывает обновление GenresList. В хранилище есть currentGenre, но это поле может поменяться только на главной странице, а ошибка вылазит при переходе на страницу с фильмом.

2022-08-26 06:50 UTC, Dima-Dim commented
> В filmScreen тоже нет setState. Но ошибка возникает вообще по компоненту GenresList. Он находится в mainScreen. Не могу понять, что вызывает обновление GenresList. В хранилище есть currentGenre, но это поле может поменяться только на главной странице, а ошибка вылазит при переходе на страницу с фильмом.

Для начала доработай использование селекторов по примеру. Вечером постараюсь посмотреть проект.

2022-08-26 07:10 UTC, LexusEgorov commented
> Оставил комментарий к коду с ссылкой на пример селектора из учебного проекта. За одно можешь посмотреть уже сам где и как они используются.

https://github.com/htmlacademy-react/guess-melody-10/pull/6/files
project/src/pages/game-screen/game-screen.tsx
15 строка. Этот пример?
Ссылку не нашел

2022-08-26 10:30 UTC, Dima-Dim commented
> > Оставил комментарий к коду с ссылкой на пример селектора из учебного проекта. За одно можешь посмотреть уже сам где и как они используются.
> 
> https://github.com/htmlacademy-react/guess-melody-10/pull/6/files project/src/pages/game-screen/game-screen.tsx 15 строка. Этот пример? Ссылку не нашел

Ссылка: https://github.com/htmlacademy-react/guess-melody-10/pull/6/files

2022-08-27 03:27 UTC, Dima-Dim commented
Пока не вижу поправленных селекторов.

2022-08-27 08:44 UTC, LexusEgorov commented
Не понимаю как сделать фильтрацию по другому

2022-08-27 09:53 UTC, Dima-Dim commented
> Не понимаю как сделать фильтрацию по другому. В примере только деструктуризация state была. Чем вообще плох вариант с createSelector?

А ты посмотрел как в учебном проекте используются селекторы? Видимо нет.
https://github.com/htmlacademy-react/guess-melody-10/blob/master/project/src/pages/game-screen/game-screen.tsx

2022-08-27 10:35 UTC, LexusEgorov commented
Да, не смотрел. Теперь вроде понял, попробую реализовать

2022-08-27 13:29 UTC, LexusEgorov commented
Надеюсь, что сейчас правильно сделал. 
Ошибка при переходе ушла. Скорее всего проблема была в том, что у меня менялись данные в хранилище (устанавливался currentFilm и currentGenre) и компонент пытался выполнить перерисовку.

2022-08-29 02:39 UTC, Dima-Dim commented on project/src/components/card/card.tsx
> +          onClick={() => {
Не нужно создавать функции внутри JSX-разметки.

2022-08-29 02:39 UTC, Dima-Dim commented on project/src/store/selectors.ts
> +    return films.filter((film) => film.genre === currentFilm.genre && film !== currentFilm).slice(0,4);
4 - магическое число.

2022-08-29 02:41 UTC, merged